# Append or merge this snippet into ~/.codex/config.toml so Codex CLI loads the subagents MCP server.
# '{{TARGET_MCP}}' will be replaced by install.sh with the absolute path to the MCP script.
[mcp_servers.subagents]
command = "node"
args = ["{{TARGET_MCP}}"]
